#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if [ -f "$par2_install_path/par2" ]; then
    ynh_script_progression "Removing par2cmdline-turbo..."
    ynh_safe_rm "$par2_install_path/par2"
fi

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

ynh_config_remove_systemd

ynh_config_remove_nginx

ynh_config_remove_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
