#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE

#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null
then
	ynh_script_progression "Removing $app service integration..."
	yunohost service remove $app
fi

ynh_config_remove_systemd

ynh_config_remove_nginx

ynh_config_remove_logrotate

# Restore original par2 if par2cmdline-turbo was installed
if [ -f "/usr/bin/par2.original" ]; then
    ynh_script_progression "Restoring original par2..."
    mv /usr/bin/par2.original /usr/bin/par2
    ynh_print_info "Original par2 restored"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
