#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet

yunohost service add $app --description="SABnzbd Usenet Client" --log="/var/log/$app/$app.log"

ynh_restore "/etc/logrotate.d/$app"

# SABnzbd doesn't use fail2ban or cron by default
# ynh_restore "/etc/fail2ban/jail.d/$app.conf"
# ynh_restore "/etc/fail2ban/filter.d/$app.conf"
# ynh_systemctl --action=restart --service=fail2ban

# Other various files...
# ynh_restore "/etc/cron.d/$app"
# ynh_restore "/etc/$app/"

#=================================================
# RELOAD NGINX AND START THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and starting $app's service..."

touch /var/log/$app/$app.log
chown -R $app:$app /var/log/$app/

ynh_systemctl --service=$app --action="start"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
